--@Autor:	Carlos Alberto Arteaga Lira
--@Fecha creacion:	05/05/2018
--@Creacion de sinonimos en cada PDB

prompt Conectandose a calbd_s1
connect consultora_bdd/consultora_bdd@calbd_s1

prompt creando sinonimos para el fragmento PAIS
CREATE OR REPLACE SYNONYM PAIS_1 FOR PAIS;
CREATE OR REPLACE SYNONYM PAIS_2 FOR PAIS@calbd_s2;

prompt creando sinonimos para el fragmento OFICINA
CREATE OR REPLACE SYNONYM OFICINA_1 FOR OFICINA;
CREATE OR REPLACE SYNONYM OFICINA_2 FOR OFICINA@calbd_s2;

prompt creando sinonimos para el fragmento PROYECTO
CREATE OR REPLACE SYNONYM PROYECTO_1 FOR PROYECTO;
CREATE OR REPLACE SYNONYM PROYECTO_2_1 FOR PROYECTO1@calbd_s2;
CREATE OR REPLACE SYNONYM PROYECTO_2_2 FOR PROYECTO2@calbd_s2;

prompt creando sinonimos para el fragmento PROYECTO_PDF
CREATE OR REPLACE SYNONYM PROYECTO_PDF_1 FOR PROYECTO_PDF;
CREATE OR REPLACE SYNONYM PROYECTO_PDF_2 FOR PROYECTO_PDF@calbd_s2;

prompt creando sinonimos para el fragmento EMPLEADO
CREATE OR REPLACE SYNONYM EMPLEADO_1 FOR EMPLEADO;
CREATE OR REPLACE SYNONYM EMPLEADO_2_1 FOR EMPLEADO@calbd_s2;
CREATE OR REPLACE SYNONYM EMPLEADO_2_2 FOR EMPLEADO2@calbd_s2;

prompt creando sinonimos para el fragmento PAGO_EMPLEADO
CREATE OR REPLACE SYNONYM PAGO_EMPLEADO_1 FOR PAGO_EMPLEADO;
CREATE OR REPLACE SYNONYM PAGO_EMPLEADO_2 FOR PAGO_EMPLEADO@calbd_s2;


prompt Conectandose a consultora_bdd en s2 
connect consultora_bdd/consultora_bdd@calbd_s2
prompt creando sinonimos para el fragmento PAIS
CREATE OR REPLACE SYNONYM PAIS_1 FOR PAIS@calbd_s1;
CREATE OR REPLACE SYNONYM PAIS_2 FOR PAIS;

prompt creando sinonimos para el fragmento OFICINA
CREATE OR REPLACE SYNONYM OFICINA_1 FOR OFICINA@calbd_s1;
CREATE OR REPLACE SYNONYM OFICINA_2 FOR OFICINA;

prompt creando sinonimos para el fragmento PROYECTO
CREATE OR REPLACE SYNONYM PROYECTO_1 FOR PROYECTO@calbd_s1;
CREATE OR REPLACE SYNONYM PROYECTO_2_1 FOR PROYECTO1;
CREATE OR REPLACE SYNONYM PROYECTO_2_2 FOR PROYECTO2;

prompt creando sinonimos para el fragmento PROYECTO_PDF
CREATE OR REPLACE SYNONYM PROYECTO_PDF_1 FOR PROYECTO_PDF@calbd_s1;
CREATE OR REPLACE SYNONYM PROYECTO_PDF_2 FOR PROYECTO_PDF;

prompt creando sinonimos para el fragmento EMPLEADO
CREATE OR REPLACE SYNONYM EMPLEADO_1 FOR EMPLEADO@calbd_s1;
CREATE OR REPLACE SYNONYM EMPLEADO_2_1 FOR EMPLEADO;
CREATE OR REPLACE SYNONYM EMPLEADO_2_2 FOR EMPLEADO2;

prompt creando sinonimos para el fragmento PAGO_EMPLEADO
CREATE OR REPLACE SYNONYM PAGO_EMPLEADO_1 FOR PAGO_EMPLEADO@calbd_s1;
CREATE OR REPLACE SYNONYM PAGO_EMPLEADO_2 FOR PAGO_EMPLEADO;

prompt listo
exit 
