--@Autor:Arteaga Lira Carlos Alberto
--@Fecha creación: 05/05/2018
--@Descripción:Script de ejecución para crear de vistas en ambas PDBs

CREATE OR REPLACE VIEW V_PAIS(
PAIS_ID, CLAVE, NOMBRE, REGION)
AS SELECT PAIS_ID, CLAVE, NOMBRE, REGION
FROM PAIS_1
UNION ALL
SELECT PAIS_ID, CLAVE, NOMBRE, REGION
FROM PAIS_2;

CREATE OR REPLACE VIEW V_OFICINA(
OFICINA_ID, NOMBRE, PAIS_ID)
AS SELECT OFICINA_ID, NOMBRE, PAIS_ID
FROM OFICINA_1
UNION ALL
SELECT OFICINA_ID, NOMBRE, PAIS_ID
FROM OFICINA_2;

CREATE OR REPLACE VIEW V_PROYECTO(
PROYECTO_ID, NOMBRE, CLAVE, FECHA_INICIO, FECHA_FIN, RESPONSABLE_ID, OFICINA_ID)
AS SELECT PROYECTO_ID, NOMBRE, CLAVE, FECHA_INICIO, FECHA_FIN, RESPONSABLE_ID, OFICINA_ID
FROM PROYECTO_1
UNION ALL
SELECT PROYECTO_ID, NOMBRE, CLAVE, FECHA_INICIO, FECHA_FIN, RESPONSABLE_ID, OFICINA_ID
FROM PROYECTO_2_1
UNION ALL
SELECT PROYECTO_ID, NOMBRE, CLAVE, FECHA_INICIO, FECHA_FIN, RESPONSABLE_ID, OFICINA_ID
FROM PROYECTO_2_2;

CREATE OR REPLACE VIEW V_PAGO_EMPLEADO(
PAGO_EMPLEADO_ID, IMPORTE, FECHA_PAGO, PROYECTO_ID, EMPLEADO_ID)
AS SELECT PAGO_EMPLEADO_ID, IMPORTE, FECHA_PAGO, PROYECTO_ID, EMPLEADO_ID
FROM PAGO_EMPLEADO_1
UNION ALL
SELECT PAGO_EMPLEADO_ID, IMPORTE, FECHA_PAGO, PROYECTO_ID, EMPLEADO_ID
FROM PAGO_EMPLEADO_2;





