

CREATE TABLE PLAN_ESTUDIOS(
	PLAN_ESTUDIOS_ID 	NUMERIC(2,0) 	NOT NULL,
	CLAVE 				VARCHAR(7)		NOT NULL,
	FECHA_APROBACION	DATE			NOT NULL,
	FECHA_INICIO		DATE			NOT NULL,
	FECHA_FIN			DATE,
	CONSTRAINT PK_PLAN_ESTUDIOS_ID PRIMARY KEY (PLAN_ESTUDIOS_ID)	
);

CREATE TABLE ASIGNATURA(
	ASIGNATURA_ID			NUMERIC(10,0)	NOT NULL,
	NOMBRE					VARCHAR(50)	NOT NULL,
	CREDITOS				NUMERIC(2,0)		NOT NULL,
	ASIGNATURA_REQUERIDA_ID	NUMERIC(10,0),
	PLAN_ESTUDIOS_ID 		NUMERIC(2,0)		NOT NULL,
	CONSTRAINT PK_ASIGNATURA_ID PRIMARY KEY (ASIGNATURA_ID),
	CONSTRAINT FK_PLAN_ESTUDIOS_ASIGNATURA_PLAN_ESTUDIOS_ID FOREIGN KEY (PLAN_ESTUDIOS_ID)
		REFERENCES PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID),
	CONSTRAINT FK_REF_ASIGNATURA_ASIGNATURA_REQUERIDA_ID FOREIGN KEY(ASIGNATURA_REQUERIDA_ID)
		REFERENCES ASIGNATURA(ASIGNATURA_ID)
);

CREATE TABLE PROFESOR(
	PROFESOR_ID			NUMERIC(10,0)	NOT NULL,
	NOMBRE				VARCHAR(50)	NOT NULL,
	APELLIDO_PATERNO	VARCHAR(50)	NOT NULL,
	APELLIDO_MATERNO	VARCHAR(50),
	RFC 				VARCHAR(18)	NOT NULL,
	FECHA_NACIMIENTO	DATE			NOT NULL,
	CONSTRAINT PK_PROFESOR_ID PRIMARY KEY(PROFESOR_ID)
);

CREATE TABLE SEMESTRE(
	SEMESTRE_ID 	NUMERIC(18,0)	NOT NULL,
	ANIO			NUMERIC(4,0)		NOT NULL,
	PERIODO			NUMERIC(1,0)		NOT NULL,
	FECHA_INICIO 	DATE			NOT NULL,
	FECHA_FIN		DATE			NOT NULL,
	CONSTRAINT PK_SEMESTRE_ID PRIMARY KEY(SEMESTRE_ID) 
);

CREATE TABLE CURSO(
	CURSO_ID		NUMERIC(10,0)	NOT NULL,
	CUPO_MAXIMO		NUMERIC(2,0)		NOT NULL,
	PROFESOR_ID 	NUMERIC(10,0)	NOT NULL,
	ASIGNATURA_ID 	NUMERIC(10,0)	NOT NULL,
	SEMESTRE_ID 	NUMERIC(18,0) 	NOT NULL,
	CLAVE_GRUPO		CHAR(3) 		NOT NULL,
	CONSTRAINT PK_CURSO_ID PRIMARY KEY(CURSO_ID),
	CONSTRAINT FK_PROFESOR_CURSO_PROFESOR_ID FOREIGN KEY(PROFESOR_ID)
		REFERENCES PROFESOR(PROFESOR_ID),
	CONSTRAINT FK_ASIGNATURA_CURSO_ASIGNATURA_ID FOREIGN KEY(ASIGNATURA_ID)
		REFERENCES ASIGNATURA(ASIGNATURA_ID),
	CONSTRAINT FK_SEMESTRE_CURSO_SEMESTER_ID FOREIGN KEY(SEMESTRE_ID)
		REFERENCES SEMESTRE(SEMESTRE_ID)
);

CREATE TABLE HORARIO(
	HORARIO_ID		NUMERIC(18,0)		NOT NULL,
	DIA_SEMANA		NUMERIC(1,0)			NOT NULL,
	HORA_INICIO		DATE				NOT NULL,
	HORA_FIN		DATE				NOT NULL,
	CONSTRAINT PK_HORARIO_ID PRIMARY KEY(HORARIO_ID)
);

CREATE TABLE CURSO_HORARIO(
	CURSO_HORARIO_ID NUMERIC(18,0) 	NOT NULL,
	CURSO_ID 		NUMERIC(10,0) 	NOT NULL,
	HORARIO_ID 		NUMERIC(18,0) 	NOT NULL,
	CONSTRAINT PK_CURSO_HORARIO_ID PRIMARY KEY(CURSO_HORARIO_ID),
	CONSTRAINT FK_CURSO_CURSO_HORARIO_CURSO_HORARIO_ID FOREIGN KEY(CURSO_ID)
		REFERENCES CURSO(CURSO_ID),
	CONSTRAINT FK_HORARIO_CURSO_HORARIO_CURSO_HORARIO_ID FOREIGN KEY(HORARIO_ID)
		REFERENCES HORARIO(HORARIO_ID)
);

CREATE TABLE ESTUDIANTE(
	ESTUDIANTE_ID 		NUMERIC(18,0)	NOT NULL,
	NOMBRE				VARCHAR(50)	NOT NULL,
	APELLIDO_PATERNO	VARCHAR(50)	NOT NULL,
	APELLIDO_MATERNO	VARCHAR(50)	NOT NULL,
	FECHA_NACIMIENTO 	DATE			NOT NULL,
	FOTOGRAFIA			BLOB			NULL,
	PLAN_ESTUDIOS_ID 	NUMERIC(2,0)		NOT NULL,
	CONSTRAINT PK_ESTUDIANTE_ID PRIMARY KEY(ESTUDIANTE_ID),
	CONSTRAINT FK_PLAN_ESTUDIOS_ESTUDIANTE_PLAN_ESTUDIOS_ID FOREIGN KEY(PLAN_ESTUDIOS_ID)
		REFERENCES PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID) 
);

CREATE TABLE ESTUDIANTE_INSCRITO(
	ESTUDIANTE_INSCRITO_ID 	NUMERIC(10,0) NOT NULL,
	CURSO_ID 				NUMERIC(10,0),
	ESTUDIANTE_ID 			NUMERIC(18,0),
	CALIFICACION 			NUMERIC(2,0),
	CONSTRAINT PK_ESTUDIANTE_INSCRITO_ID PRIMARY KEY(ESTUDIANTE_INSCRITO_ID),
	CONSTRAINT FK_CURSO_ESTUDIANTE_INSCRITO_CURSO_ID FOREIGN KEY(CURSO_ID)
		REFERENCES CURSO(CURSO_ID),
	CONSTRAINT FK_ESTUDIANTE_ESTUDIANTE_INSCRITO_ESTUDIANTE_ID FOREIGN KEY(ESTUDIANTE_ID)
		REFERENCES ESTUDIANTE(ESTUDIANTE_ID)
);

CREATE TABLE ESTUDIANTE_EXTRAORDINARIO(
	ESTUDIANTE_ID 		NUMERIC(18,0)	NOT NULL,
	NUM_EXAMEN			NUMERIC(3,0)		NOT NULL,
	CALIFICACION 		NUMERIC(3,1)		NOT NULL,
	ASIGNATURA_ID 		NUMERIC(10,0)	NOT NULL,
	CONSTRAINT PK_ESTUDIANTE_ID_NUM_EXAMEN PRIMARY KEY(ESTUDIANTE_ID, NUM_EXAMEN),
	CONSTRAINT  FK_ASIGNATURA_ESTUDIANTE_EXTRAORDINARIO_ASIGNATURA_ID FOREIGN KEY(ASIGNATURA_ID)
		REFERENCES ASIGNATURA(ASIGNATURA_ID)
);
